services:
  postgres14:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: leo66_production
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./leo66_production.sql:/leo66_production.sql
      # psql -U postgres leo66_production < /leo66_production.sql
      
  # adminer:
  #   image: adminer
  #   # restart: always
  #   ports:
  #     - 8080:8080
      
  rails-server: &app
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    restart: always
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - postgres14
    environment:
      DATABASE_URL: postgres://postgres:password@postgres14:5432/leo66_production
      RAILS_ENV: production
      SECRET_KEY_BASE: 6362668d43016a8c3a9050acd083906756dcffda2be3224df732a284b59dfe56f6641f429c87dad445ff9b940a51cfc23169639d5857ad9e8632f3f33f906fdf
      RAILS_SERVE_STATIC_FILES: true
    tmpfs:
      - /tmp
      
  db-migrate:
    <<: *app
    command: bundle exec rails db:create #db:migrate
    restart: "no"
    ports: []

  assets-compile:
    <<: *app
    command: bundle exec rails assets:compile
    restart: "no"
    ports: []
  
volumes:
  gem_cache:
  db_data:
  node_modules:     