# !!! Используй общий файл для сервера


services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: leo66_production
    volumes:
      - db_data:/var/lib/postgresql/data
      # - ./leo66_production.sql:/leo66_production.sql
      ## psql -U postgres leo66_production < /leo66_production.sql

  rails_app: &app
    build: .
    command: bundle exec rails s -p 5001 -b '0.0.0.0'
    restart: always
    volumes:
      - ../_leo66_files/assets:/rails_app/public/assets
      - ../_leo66_files/ckeditor_assets:/rails_app/public/ckeditor_assets
      - ../_leo66_files/files:/rails_app/public/files
      - ../_leo66_files/images:/rails_app/public/images
    ports:
      - 5001:5001
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/leo66_production
      RAILS_ENV: production
      SECRET_KEY_BASE: 6362668d43016a8c3a9050acd083906756dcffda2be3224df732a284b59dfe56f6641f429c87dad445ff9b940a51cfc23169639d5857ad9e8632f3f33f906fdf
      RAILS_SERVE_STATIC_FILES: true
      RAILS_LOG_TO_STDOUT: true
    tmpfs:
      - /tmp

  # db-migrate:
  #   <<: *app
  #   command: bundle exec rails db:create #db:migrate
  #   restart: "no"
  #   ports: []
  #
  # assets-compile:
  #   <<: *app
  #   command: bundle exec rails assets:precompile
  #   restart: "no"
  #   ports: []

networks:
  default:
    external: true
    name: slam_network

volumes:
  db_data:
