# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3618000f42306bdab5489fcb2cd84449a5759c94ce539861a53f5c07913e35c8b82459b0620f28c96c2c8ade053b115ee7f1a811326a51664162541924089718

test:
  secret_key_base: 16afb64ff872d8f65fde25f6d53052214dfe682afc7074a0c3fe320962b1d5a90b099bccc9316ab9dc80df684319190799f80b61e713f6e44d411c2b21436a11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
